# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SceneProto.proto',
  package='Base',
  serialized_pb=_b('\n\x10SceneProto.proto\x12\x04\x42\x61se\".\n\nSceneProto\x12\r\n\x02id\x18\x01 \x02(\x05:\x01\x30\x12\x11\n\x06treeId\x18\x02 \x02(\x05:\x01\x30\"3\n\x10SceneProto_ARRAY\x12\x1f\n\x05items\x18\x01 \x03(\x0b\x32\x10.Base.SceneProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SCENEPROTO = _descriptor.Descriptor(
  name='SceneProto',
  full_name='Base.SceneProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Base.SceneProto.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='treeId', full_name='Base.SceneProto.treeId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=72,
)


_SCENEPROTO_ARRAY = _descriptor.Descriptor(
  name='SceneProto_ARRAY',
  full_name='Base.SceneProto_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='Base.SceneProto_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=125,
)

_SCENEPROTO_ARRAY.fields_by_name['items'].message_type = _SCENEPROTO
DESCRIPTOR.message_types_by_name['SceneProto'] = _SCENEPROTO
DESCRIPTOR.message_types_by_name['SceneProto_ARRAY'] = _SCENEPROTO_ARRAY

SceneProto = _reflection.GeneratedProtocolMessageType('SceneProto', (_message.Message,), dict(
  DESCRIPTOR = _SCENEPROTO,
  __module__ = 'SceneProto_pb2'
  # @@protoc_insertion_point(class_scope:Base.SceneProto)
  ))
_sym_db.RegisterMessage(SceneProto)

SceneProto_ARRAY = _reflection.GeneratedProtocolMessageType('SceneProto_ARRAY', (_message.Message,), dict(
  DESCRIPTOR = _SCENEPROTO_ARRAY,
  __module__ = 'SceneProto_pb2'
  # @@protoc_insertion_point(class_scope:Base.SceneProto_ARRAY)
  ))
_sym_db.RegisterMessage(SceneProto_ARRAY)


# @@protoc_insertion_point(module_scope)
